[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "Hot4S2HDwRYp4YVw1cEUqMcHkvRDWfPfAqLxGG7ndZbN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test_ts = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test = "cargo test-sbf"